sudo: false
language: go
go_import_path: github.com/go-redis/redis

services:
  - redis-server

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
